// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjnWx6aeptnSZclkkYPCTCOJlOy20dptQ',
    appId: '1:628112947910:web:99b8c9a365daa60c82f5c7',
    messagingSenderId: '628112947910',
    projectId: 'test-c4d69',
    authDomain: 'test-c4d69.firebaseapp.com',
    storageBucket: 'test-c4d69.firebasestorage.app',
    measurementId: 'G-V48X0JHY9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJsuU7FZ4cDMeGQPD1lS4y7oD0CV3F41o',
    appId: '1:628112947910:android:549cf6d65572193382f5c7',
    messagingSenderId: '628112947910',
    projectId: 'test-c4d69',
    storageBucket: 'test-c4d69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGeuCo3UnCfuppfdIMf9yKl_-4XS8gyr4',
    appId: '1:628112947910:ios:f126e4210e2b176782f5c7',
    messagingSenderId: '628112947910',
    projectId: 'test-c4d69',
    storageBucket: 'test-c4d69.firebasestorage.app',
    iosBundleId: 'com.example.skilltest',
  );
}
